### ISSUE TITLE
Running the test crashes with the following output

### ISSUE THREAD

**Issue by SyntaxPolice** [momahajogami/Prime-Numbers#5]
When I run "python test*" I get this output now:

Traceback (most recent call last):
  File "test_poly_divmod.py", line 102, in <module>
    unittest.main()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 94, in **init**
    self.parseArgs(argv)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_poly_gcd'

**Comment by momahajogami** [comment]
That's pretty puzzling.

Especially since if you just type "python testing.py", you don't get the
error.

I'll work on this now.

**Comment by momahajogami** [comment]
Oh, I mean that makes sense.

I guess you shouldn't type "python test*" but rather python each test
separately.

I probably ought to write a script to do this as you suggest.

**Comment by momahajogami** [comment]
Well, I wrote a test.sh, but you beat me to the commitment.

So I edited your script runTests.sh.  Try it now.

**Comment by SyntaxPolice** [comment]
But you forgot to remove runTest.sh!! Don't worry, I sent you a new PR. By
the way when you reply to these emails, they're public in the bug tracker:
https://github.com/momahajogami/Prime-Numbers/issues/5

Here's the PR:
https://github.com/momahajogami/Prime-Numbers/pull/6

**Comment by SyntaxPolice** [comment]
Oh, and you can close this issue because it seems to work now.

**Comment by momahajogami** [comment]
Well, it looks like you deleted your own runTest.sh while I deleted my
test.sh, each in favor of the other's script.

Would it be appropriate to invoke my authority at this point to retain your
title run.sh?

Also, I may have invented a test which breaks poly_prime_gcd in a
substantial way.  Give me an hour on this one.

**Comment by SyntaxPolice** [comment]
Well, when I look at your repo on here, it looks like you still have both
files. Maybe you forgot to push your changes?
https://github.com/momahajogami/Prime-Numbers

Yes, you can resolve it however you want! But my new version of test.py is
sweet.

peace.
